# Generated by Django 4.0 on 2021-12-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'Multiple Choice'), (2, 'Fill In The Blank'), (3, 'True Or False'), (4, 'Short Answer')], default=4),
        ),
    ]
